seed: 0
data_root_dir: data/latent_reps
dataset: zzz
experiment_var:
  ansatz: [original_ansatz, ansatz_skip, new_ansatzv0, new_ansatzv2, new_ansatzv3, new_ansatzv6, new_ansatzv7, new_ansatzv8, new_ansatzv9, new_ansatzv10, new_ansatzv11]
validation_size: 10000
test_size: 5000
k_folds: 1
save_dir: ansatz_experiment_inp8
q_palette: ["#6a45c2", "#63a122", "#d129b4", "#0ec61c", "#f53a4c", "#38acc1", "#723240", "#94a6fd", "#20502e", "#f68d92", "#1e438d"]
c_palette: ["#6a45c2", "#63a122", "#d129b4", "#0ec61c", "#f53a4c", "#38acc1", "#723240", "#94a6fd", "#20502e", "#f68d92", "#1e438d"]

data:
  root_dir: data/latent_reps
  scale: True
  latent_rep: 8
  transform: !!python/object:utils.Permute
    permutation: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

classical:
  input_size: 16
  latent_size: 8
  batch_size: 50
  train_size: 1000
  epochs: 500
  optimiser: adam
  loss: mse
  lr: 0.01
  eval_interval: 5
  disable_bar: True
  
quantum:
  ansatz: original_ansatz
  input_size: 8
  latent_size: 4
  layers: 1
  embedding: particle_embedding
  batch_size: 50
  train_size: 1000
  epochs: 100
  loss: fidelity_loss
  optimiser: AdamOptimizer
  lr: 0.005
  weight_init_range: [0,1]
  weight_init_dist: uniform
  eval_interval: 5
  disable_bar: True